# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.IntegerField(default=0)),
                ('valor', models.IntegerField(default=0)),
                ('cheque_fecha', models.DateTimeField(verbose_name='cheque fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=200)),
                ('total', models.IntegerField(default=0)),
                ('factura_fecha', models.DateTimeField(verbose_name='factura fecha')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chrima.Cheque')),
            ],
        ),
    ]
