# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chrima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cheque_mes',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_archivo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='folio',
            field=models.CharField(max_length=60),
        ),
    ]
