# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chrima', '0002_auto_20161015_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='cheque_no',
            field=models.CharField(max_length=20),
        ),
    ]
