# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pliroforia', '0002_auto_20161021_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalizador',
            name='num',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='catalizador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
