# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pliroforia', '0003_auto_20161021_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalizador',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='catalizador',
            name='código',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
